logging:
    level:
        org:
            springframework:
                web: DEBUG
spring:
    batch:
        job:
            enabled: false
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:xe
        username: boot
        password: boot
