spring:
    datasource:
        url: jdbc:mysql://rm-wz939g2zz921yd9rjo.mysql.rds.aliyuncs.com:3306/spring-boot-breaker?characterEncoding=utf8&useSSL=true
        username: root
        password: Jack123!
    jackson:
        serialization:
            indent_output: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
