author:
    age: 32
    name: wyf

book:
    author: wangyunfei
    name: spring boot

logging:
    file: D:/mylog/log.log
    level:
        org:
            springframework:
                web: DEBUG

server:
    port: 9090
    context-path: /helloboot
